version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGO_URI: "mongodb://mongo:27017/assignement"
      JWT_SECRET: "JWT_SECRETAHBODHAIOUDGBAIUODGVAUIDVBAIU"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_APP_BASE_URL: "http://backend:3000"

volumes:
  mongo_data:
